version: '2'

services:
  app:
    image: 'helloapp.jar.jar:latest'
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - dbs    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: dbss
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=!
      - POSTGRES_DB=test
     
    expose:
      - "5432:5432" 
volumes:
  dbsaaa:
    driver: local